### PR TITLE
Sync fork with upstream

### PR DESCRIPTION
**Pull request by MechanicalTyler**
This PR rebases off of strangelove-ventures/lens, and merges changes from main.

This gives us the cosmos-sdk upgrades that we need for https://github.com/VolumeFi/paloma/issues/115

### CODE REVIEW

**Comment by MechanicalTyler** [comment]
This is ready for review.  There is one remaining bug in that goreleaser fails for darwin_arm64.  This bug is actually present in upstream strangelove-ventures/lens as well.  It can be addressed in a follow-up PR.

**Comment by taariq** [comment]
Got it. Looks like it wasn't that bad and didn't require extensive refactoring of Matijia's updates. Good news

**Review by taariq — APPROVED** [review]
Okay. Let's do it. We have upgrade lens for CometBFT! LFG!

**Comment by taariq** [comment]
@ToasterTheBrave do we want to remove the offending goreleaser for darwin here too?

**Pull request merged**
